// src/data/toothpastes.ts
import { Toothpaste } from "../types/Toothpaste";

export const toothpastes: Toothpaste[] = [
    // Existing entries
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste A",
      ageGroup: "6+ years",
      fluorideContent: 1000,
      benefits: "Whitening, Anti-cavity",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste B",
      ageGroup: "All ages",
      fluorideContent: 1450,
      benefits: "Sensitive teeth relief",
    },
    // New entries
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste C",
      ageGroup: "All ages",
      fluorideContent: 1100,
      benefits: "Plaque control, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste D",
      ageGroup: "2+ years",
      fluorideContent: 500,
      benefits: "Children's formula, Cavity protection",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste E",
      ageGroup: "6+ years",
      fluorideContent: 1400,
      benefits: "Enamel strengthening, Whitening",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste F",
      ageGroup: "All ages",
      fluorideContent: 1300,
      benefits: "Anti-bacterial, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste G",
      ageGroup: "3+ years",
      fluorideContent: 700,
      benefits: "Natural ingredients, Gentle",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste H",
      ageGroup: "All ages",
      fluorideContent: 1500,
      benefits: "Advanced protection, Whitening",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste I",
      ageGroup: "6+ years",
      fluorideContent: 1200,
      benefits: "Tartar control, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste J",
      ageGroup: "2+ years",
      fluorideContent: 600,
      benefits: "Mild, Kid-friendly",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste K",
      ageGroup: "All ages",
      fluorideContent: 1000,
      benefits: "Daily use, Plaque removal",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste L",
      ageGroup: "6+ years",
      fluorideContent: 1400,
      benefits: "Anti-cavity, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste M",
      ageGroup: "All ages",
      fluorideContent: 1300,
      benefits: "Whitening, Enamel protection",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste N",
      ageGroup: "3+ years",
      fluorideContent: 800,
      benefits: "Sensitive teeth relief, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste O",
      ageGroup: "6+ years",
      fluorideContent: 1100,
      benefits: "Whitening, Anti-bacterial",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste P",
      ageGroup: "All ages",
      fluorideContent: 1200,
      benefits: "Plaque control, Tartar prevention",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste Q",
      ageGroup: "2+ years",
      fluorideContent: 500,
      benefits: "Gentle formula, Cavity protection",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste R",
      ageGroup: "All ages",
      fluorideContent: 1400,
      benefits: "Advanced protection, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste S",
      ageGroup: "6+ years",
      fluorideContent: 1000,
      benefits: "Enamel strengthening, Whitening",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste T",
      ageGroup: "3+ years",
      fluorideContent: 700,
      benefits: "Natural ingredients, Sensitive teeth relief",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste U",
      ageGroup: "All ages",
      fluorideContent: 1500,
      benefits: "Whitening, Tartar control",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste V",
      ageGroup: "6+ years",
      fluorideContent: 1200,
      benefits: "Anti-cavity, Fresh breath",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste W",
      ageGroup: "All ages",
      fluorideContent: 1300,
      benefits: "Whitening, Plaque control",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste X",
      ageGroup: "2+ years",
      fluorideContent: 600,
      benefits: "Mild, Cavity protection",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste Y",
      ageGroup: "All ages",
      fluorideContent: 1400,
      benefits: "Plaque control, Whitening",
    },
    {
      image: "data:image/png;base64,...",
      name: "Toothpaste Z",
      ageGroup: "6+ years",
      fluorideContent: 1000,
      benefits: "Anti-bacterial, Fresh breath",
    },
  ];
  
